### ISSUE TITLE
Can't consistently trigger webhooks for menu changes 

### ISSUE THREAD

**Issue by edtjones** [rooftopcms/rooftop-queue-pusher#1]
I haven't tested as thoroughly as I should have, but I'm having trouble getting webhooks into the queue when making changes to menus - adding items, changing titles etc. Menus are taxonomies so maybe there is another hook we need to add?

**Comment by phendrick** [comment]
These issues should be resolved by https://github.com/rooftopcms/rooftop-queue-pusher/commit/4fa113346d81dc4411e5b72d1be90fec0e24f748
